# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: en-US
title: "Techpool X"
description: "Thoughts inspired by technology."

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: # the subpath of your site, e.g. "/blog"

# the base hostname & protocol for your site e.g. "https://www.example.com"
url: https://www.techpoolx.com

logo: "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: techpoolx
twitter:
  username: techpoolx

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /blog/:title.html
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
category_archive_path: "/blog/categories/#"
tag_archive_path: "/blog/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true

# Site Author
author:
  name: techpoolx
  picture: /images/logo.png
  email:
  twitter:
  links:
    - title: Twitter
      url: https://twitter.com/techpoolx
      icon: fab fa-twitter-square
    - title: Email
      url: mailto:techpoolx@gmail.com
      icon: fas fa-envelope-square
 
# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/techpoolx
    icon: fab fa-twitter-square
  - title: Email
    url: mailto:techpoolx@gmail.com
    icon: fas fa-envelope-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

